### ISSUE TITLE
[feature-request]: add calendar, date-picker, and time-picker components

### ISSUE THREAD

**Issue by glyad** [aurelia-ui-toolkits/aurelia-mdc-web#8]
Intention:
- Components mentioned above are must-have components

**Comment by MaximBalaganskiy** [comment]
The datepicker may soon be implemented https://github.com/material-components/material-components-web/issues/55. I'd rather wait for original implementation. In the meantime you can use the one suggested in the issue above.

As for other pickers, these are not trivial components. I'm afraid I don't have much time resource for them unless it's needed for our organisation projects. At the moment, default browser pickers look quite decent even on a desktop.

I would definitely consider a PR though.

**Comment by glyad** [comment]
I mostly agree with your answer(s), but... 
1. The original issue mentioned is from 2016. :)
2. The browser pickers are OK, but sometime we need the calendar component independently. It means, we may miss the Calendar component, which is shareable part of custom pickers.

What do you think regarding to use the Aurelia-UX controls (DatePicker, etc.) together with Aurelia-MDC in same project? Possible incompatibility issues? Reusing the code of UX with MDC styles?

...and Thank You a Lot for your great work

**Comment by MaximBalaganskiy** [comment]
From my point of view, the issue with these components is that MWC team tends to provide smaller blocks only, leaving the bigger pieces to us. 

I'm not against adding something like that into the library, as I've already done with expandable, lookup, and tree view for example. It's just I've already stretched my organisation desire to support an open source project and don't want to push too much - hard to justify the need for us at the moment. 

Mixing MDC and UX should not be a problem as they follow BEM and don't pollute global scope. I would be wary about UX though - it's not officially abandoned but has very little traction. I thought I would give it a kick by contributing some missing components but that was a wasted effort in my opinion.

**Comment by adriatic** [comment]
@glyad allow me a bit of history: The work on the collection of "Aurelia Bridges" started nearly 6 years ago, on my initiative driven by the desire to get Aurelia developers to access to a "state of the art" UI. I was lucky that my first partner in this project was a brilliant developer @JeroenVinke, who joined me driven initially by the need to use KendoUI in one of his projects. Soon after that @Thanood picked up the abstraction layer designed by Jeroen and created the basic implementation of [Materialize bridge](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge), by that time a small team from Syncfusion used the same abstraction layer to create the [syncfusion bridge](https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge).

Now, several years after most of the original developers (with the notable exception of Jeroen, who still shows up to see whether there is something that requires his level of expertise) only two most "faithful" guys are still present - despite having full-time jobs. While [everyone who uses Aurelia](https://www.reddit.com/r/javascript/comments/8a7bwi/anyone_else_using_aurelia_javascript_framework/) loves it, there are not enough sich "lovers" to maintain its momentum. I left Aurelia for Vue and then discovered Svelte.

My point is that this project (MDC) is very much understaffed, so in order to help the team (@MaximBalaganskiy), please consider creating a few PRs.

**Comment by MaximBalaganskiy** [comment]
@adriatic how do you find vue and svelte now that you've compared?

**Comment by glyad** [comment]
@adriatic, I understand both each of your statements and that what is behind of the words as well.

I follow Aurelia since 2016 and try "to sell" it to our clients, but only two of our valuable clients agreed to use Aurelia. This reminds me the battle of Caliburn.Micro against Prism. You may present two frameworks side-by-side, show, how CM really answers all of the needs in simple elegant way, how it's simple to learn, how it lightweight vs. Prism... Anyway, comes somebody from managers, who is far from the programming usually, and says something like as "but it's of Microsoft" or "but it has the bigger community".  Why? There are armies of so called consultors in each country, which need to promote their businesses. Agree, it's simpler "to sell" _Microsoft's_ Prism, or _Google's_ Angular, or _Facebook's_ "React".  It defends consultors in case of the failure of the project. It's more simple to company middle management to explain failures with a wrong choice of the dev. platform  (some of the calls from our clients sounds like as "help us to transit from Angular to React" or vice versa). The conclusion is very simple also: Aurelia needs her betrothed, her "Google" or "Facebook". 

Like as all of the contributions to open-source, both of mine and of my team (github.com/logofx), and of Aurelia bakers as well, the possible contribution to that project is constrained with full-time job. Most of LogoFX contributions were derived from real needs of certain customer's projects, as common case solutions. Anyway, I'm still believing in the collective mind for Aurelia future. I hope, we will find the project to probe Aurelia and MDC and it will allow us to contribute all of the missing components to this project and not only. 

Sorry for off-topic discussion initiated. :)

**Comment by adriatic** [comment]
@MaximBalaganskiy: comparison between Vue and Svelte needs to take in account everything that @glyad explained **[above](https://github.com/aurelia-ui-toolkits/aurelia-mdc-web/issues/8#issuecomment-678848862)**.
Vue is not nearly as sophisticated as Aurelia - but it has significant forward momentum and orders of magnitude of developers that know how to use it. 

@glyad In the early nineties, I was leading a team that created a lot better Java VM and the libraries that were 100 times richer than what Sun shipped initially. In addition, our Java was developed completely independent from Sun, so we rightfully expected to take the "world over" - only to realize that Sun's marketing machine could just placate the developers with "not blessed" by Sun - and that was sufficient to stop us dead in the water. So, I really understand what you are saying 😢 

P.S. I do appreciate your initiated discussion since it is really not off-topic for neither of us.

**Comment by MaximBalaganskiy** [comment]
FYI https://github.com/aurelia-toolkit/aurelia-toolkit/tree/master/packages/mdc-datepicker
